blog/urls.py
from django.conf.urls import url

from .views import post_detail, PostList

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        {'parent_template': 'base.html'},
        name = 'blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        {'parent_template': 'base.html'},
        name = 'blog_post_detail'),
]

organizer/urls.py
from django.conf.urls import url

from .views import (startup_detail, startup_list, tag_detail, tag_list)

urlpatterns = [
    url(r'^startup/$',
        startup_list,
        name = 'organizer_startup_list'),
    url(r'^startup/(?P<slug>[\w\-]+)/$',
        startup_detail,
        name = 'organizer_startup_detail'),
    url(r'^tag/$',
        tag_list,
        name = 'organizer_tag_list'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',
        tag_detail,
        name = 'organizer_tag_detail'),
]

suorganizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from organizer import urls as organizer_urls
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(organizer_urls)),
    url(r'^blog/', include(blog_urls)),
]

blog/models.py
from django.db import models
from organizer.models import Startup, Tag
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, help_text='A lable for URL '
                                                     'config',
                            unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

    def __str__(self):
        return "{} on {}".format(self.title, self.pub_date.strftime('%Y-%m-%d'))

    class Meta:
        verbose_name = 'blog post'
        ordering=['-pub_date','title']
        get_latest_by='pub_date'

organizer/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=31, unique = True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label '
                                                                  'for URL '
                                                                  'config.')

    def __str__(self):
        return self.name.title()

    class Meta:
        ordering=['name']


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index = True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label '
                                                                  'for URL '
                                                                  'config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name.title()

    class Meta:
        ordering=['name']
        get_latest_by='founded_date'


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)

    def __str__(self):
        return "{}:{}".format(self.startup, self.title)

    class Meta:
        verbose_name='news article'
        ordering=['-pub_date']
        get_latest_by='pub_date'

blog/views.py
from django.shortcuts import (
    get_object_or_404, render)
from django.views.generic import View

from .models import Post
# Create your views here.


class PostList(View):

    def get(self, request, parent_template=None):
        return render(
            request,
            'blog/post_list.html',
            {'post_list': Post.objects.all(),
             'parent_template': parent_template}
        )


def post_detail(request, year, month,
                slug, parent_template=None):
    post = get_object_or_404(Post,
                             pub_date__year = year,
                             pub_date__month = month,
                             slug = slug)
    return render(
        request,
        'blog/post_detail.html',
        {'post': post,
         'parent_template': parent_template})

organizer/views.py
from django.shortcuts import render
from django.http.response import (HttpResponse, Http404)
from django.template import Context, loader
from django.shortcuts import get_object_or_404

from .models import Tag, Startup


# Create your views here.


def tag_list(request):
    return render(request, 'organizer/tag_list.html',
                              {'tag_list':
                                   Tag.objects.all()})


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request, 'organizer/tag_detail.html',
                     {'tag': tag})


def startup_list(request):
    return render(request, 'organizer/startup_list.html',
                  {'startup_list':
                        Startup.objects.all()})


def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact = slug)
    return render(
        request,
        'organizer/startup_detail.html',
        {'startup': startup}
    )

blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
<article>

    <header>
        <h2>{{ post.title|title }}</h2>
        <p>
            Written on
            <time datetime=""{{ post.pub_date|date:"Y-m-d" }}>
                {{ post.pub_date|date:"l, F j, Y" }}
            </time>
        </p>
    </header>

    {{ post.text|linebreaks }}

    {% if post.startups.all or post.tags.all %}
        <footer>

            {% if post.startups.all %}
                <section>
                    <h3>Startup{{ post.startups.count|pluralize }}</h3>
                    <ul>
                        {% for startup in post.startups.all %}
                            <li><a href="">
                                {{ startups.name }}
                            </a></li>
                        {% endfor %}

                    </ul>
                </section>
            {% endif %}

            {% if post.tags.all %}
                <section>
                    <h3>Tag{{ post.tags.count|pluralize }}</h3>
                    <ul>
                        {% for tag in post.tags.all %}
                            <li><a href="">
                                {{ tag.name|title }}
                            </a></li>
                        {% endfor %}
                    </ul>
                </section>
            {% endif %}

        </footer>
    {% endif %}

</article>
{% endblock %}

blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - post
{% endblock %}

{% block content %}
{% for post in post_list %}
    <article>
        <header>
            <h2>
                <a href="">
                    {{ post.title|title }}
                </a>
            </h2>
            <p>
                Written on:
                <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                    {{ post.pub_date|date:"l, F j, Y" }}
                </time>
            </p>
        </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p>
            <a href="">
                Read more&hellip;</a>
        </p>
    </article>
{% empty %}
    <p><em>No Blog Posts Available</em></p>
{% endfor %}
{% endblock %}

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
<article>

    <h2> {{ startup.name }}</h2>
    <dl>
        <dt>Date Founded</dt>
            <dd>{{ startup.founded_date|date:"F js, Y" }}</dd>
        <dt>Website</dt>
            <dd>{{ startup.website|urlize }}</dd>
        <dt>Contact</dt>
            <dd>{{ startup.contact }}</dd>

        <dt>Tag{{ startup.tags.count|pluralize }}</dt>
            {% for tag in startup.tags.all %}
                <dd><a href="">
                    {{ tag.name|title }}
                    </a></dd>
            {% endfor %}

    </dl>

    <p>{{ startup.description|linebreaks }}</p>

        {% if startup.newslink_set.all %}
            <section>
                <h3>Recent News</h3>
                <ul>
                    {% for newslink in startup.newslink_set.all %}
                        <li>
                            <a href=""{{ newlink.link }}>
                                {{ newslink.title|title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        {%  if startup.blog_posts.all %}
            <section>
                <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
                <ul>
                    {% for post in startup.blog_posts.all %}
                        <li>
                            <a href="">
                                {{ posts.title|title }}
                            </a>
                        </li>
                   {% endfor %}
                </ul>
            </section>
        {% endif %}

</article>
{% endblock %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startup
{% endblock %}

{% block content %}
<h2>Startup List</h2>
<ul>
    {% for startup in startup_list %}
        <li>
            <a href="">
                {{ startup.name }}
            </a>
        </li>
    {% empty %}
        <li><em>No Startups Available</em></li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
<h2> {{  tag.name|title }} </h2>
{%  if tag.startup_set.all %}
    <section>
        <h3>Startups{{ tag.startup_set.count|pluralize }}</h3>
        <p>
            Tag us associated with
            {{ tag.startup_set.count }}
            startup{{ tag.startup.count|pluralize }}
        </p>
        <ul>
            {% for startup in tag.startup_set.all %}
                <li><a href="">
                    {{ startup.name }}
                </a></li>
            {%  endfor %}
        </ul>
    </section>
{% else %}
    <p>This tag is not related to any startups.</p>
{% endif %}
    <h2></h2>
    {% if tag.blog_posts.all %}
        <section>
            <h3>Blog Posts{{ tag.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in tab.blog_posts.all %}
                    <li><a=href="">
                        {{ post.title|title }}
                    </a></li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {%  if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
    {% endif %}
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{  block.super }} - Tag List
{% endblock %}

{% block content %}
<h2>Tag List</h2>
<ul>
    {% for tag in tag_list %}
        <li>
            <a href="">
            {{ tag.name|title }}</a>
        </li>
    {% empty %}
        <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Startup Organizer
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge,chrome=1">
    <meta name="viewport" content=""width="device-width, initial-scale=1">
    <!--[if IE]><script
        src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
</head>

<body>

    <div><!--container-->
        <header>
            <h1>Startup Organizer</h1>
        </header>
        <main>
            {% block content %}
            This is default content!
            {% endblock %}
        </main>
    </div><!-- container -->

    <footer>
        <p>
            &copy;2015
            <a href="https://AndrewsForge.com/">
                Andrew Pinkham
            </a>
        </p>
        <p>
            Created for
            <a href="https://Django-Unleashed.com/"></a>
        </p>
    </footer>

</body>

</html>